name: Bug Report
description: Report a bug or unexpected behaviour
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill in as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "When I click X, Y happens instead of Z."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the behaviour.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / recordings
      description: If applicable, add screenshots or a screen recording to help explain your problem.

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "e.g. macOS 14, Windows 11, Ubuntu 22.04"

  - type: input
    id: browser
    attributes:
      label: Browser & version
      placeholder: "e.g. Chrome 122, Firefox 123, Safari 17"

  - type: input
    id: node
    attributes:
      label: Node.js version
      placeholder: "e.g. 20.11.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information that might be relevant.
